export { default as Homepage } from './Homepage'
export { default as Music } from './Music'
export { default as Notification } from './Notification'
export { default as UserProfile } from './UserProfile'
export { default as Login } from './Login'
export { default as Register } from './Register'
